import 'dart:io';
import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../../core/database/belonging_meta.dart';
import '../../../core/utilities/money.dart';
import '../../../shared/services/warranty_service.dart';
import 'inventory_report.dart';

/// Builds a professional multi-page PDF inventory report from an
/// [InventoryReport].
///
/// Rules (from the Phase 11 spec):
/// - Only available data is shown; missing fields are simply omitted —
///   never invented. A missing receipt is never faked.
/// - No legal claims: the report documents what the user recorded; it does
///   not determine coverage or guarantee reimbursement.
/// - Pure Dart (`package:pdf`), so it works identically on Android and iOS.
///
/// Photos are embedded at most one per item (the cover photo) and any
/// unreadable image is skipped rather than failing the whole report.
class PdfReportBuilder {
  PdfReportBuilder({DateFormat? dateFormat})
    : _dateFormat = dateFormat ?? DateFormat.yMMMd();

  final DateFormat _dateFormat;

  /// The PDF's built-in Helvetica only covers WinAnsi: characters like the
  /// em dash have no glyph and would render blank (with a console
  /// warning). Map the punctuation this builder itself emits to ASCII
  /// equivalents; other user text passes through unchanged.
  static String _clean(String s) => s.replaceAll('—', '-').replaceAll('–', '-');

  /// Generates the PDF bytes for [report].
  Future<Uint8List> build(InventoryReport report) async {
    final doc = pw.Document(
      title: 'KEEPIT — ${report.title}',
      author: 'KEEPIT',
    );

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        header: (context) => _pageHeader(report, context),
        footer: (context) => _pageFooter(context),
        build: (context) => [
          _titleBlock(report),
          pw.SizedBox(height: 16),
          if (report.items.isEmpty)
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 24),
              child: pw.Text(
                'No items in this report.',
                style: const pw.TextStyle(fontSize: 12),
              ),
            ),
          for (final item in report.items) ...[
            _itemSection(item),
            pw.SizedBox(height: 12),
          ],
          if (report.missingInfo.isNotEmpty) ...[
            pw.SizedBox(height: 8),
            _missingInfoAppendix(report),
          ],
          pw.SizedBox(height: 24),
          _disclaimer(),
        ],
      ),
    );

    return doc.save();
  }

  // -- page chrome ----------------------------------------------------------

  pw.Widget _pageHeader(InventoryReport report, pw.Context context) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'KEEPIT',
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
            ),
            pw.Text(
              'Inventory Report',
              style: const pw.TextStyle(fontSize: 10),
            ),
          ],
        ),
        pw.Divider(),
      ],
    );
  }

  pw.Widget _pageFooter(pw.Context context) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          'Generated by KEEPIT - for documentation only, not legal advice.',
          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
        ),
        pw.Text(
          'Page ${context.pageNumber} of ${context.pagesCount}',
          style: const pw.TextStyle(fontSize: 8),
        ),
      ],
    );
  }

  // -- title block ------------------------------------------------------------

  pw.Widget _titleBlock(InventoryReport report) {
    final rows = <List<String>>[
      ['Generated', _dateFormat.format(report.generatedAt)],
      ['Items', '${report.items.length}'],
    ];
    if (report.valuedItemCount > 0) {
      rows.add([
        'Total known value',
        // Currency varies per item; report the raw sum in the most common
        // currency among valued items to avoid inventing conversions.
        _totalValueLabel(report),
      ]);
    }
    if (report.incompleteCount > 0) {
      rows.add(['Items missing information', '${report.incompleteCount}']);
    }
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          _clean(report.title),
          style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 8),
        pw.Table(
          columnWidths: {
            0: const pw.FixedColumnWidth(150),
            1: const pw.FlexColumnWidth(),
          },
          children: [
            for (final row in rows)
              pw.TableRow(
                children: [
                  pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(vertical: 2),
                    child: pw.Text(
                      row[0],
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(vertical: 2),
                    child: pw.Text(
                      row[1],
                      style: const pw.TextStyle(fontSize: 10),
                    ),
                  ),
                ],
              ),
          ],
        ),
        pw.Divider(),
      ],
    );
  }

  /// Sums values per currency and labels the total with the most common
  /// currency. Never converts between currencies (that would invent data).
  String _totalValueLabel(InventoryReport report) {
    final perCurrency = report.valueByCurrency;
    if (perCurrency.isEmpty) return '—';
    final top = perCurrency.entries.reduce(
      (a, b) => a.value >= b.value ? a : b,
    );
    var label = formatMoney(top.value, top.key);
    final others = perCurrency.entries.where((e) => e.key != top.key);
    for (final e in others) {
      label += ' + ${formatMoney(e.value, e.key)}';
    }
    return label;
  }

  // -- item section -------------------------------------------------------------

  pw.Widget _itemSection(ReportItem item) {
    final b = item.belonging;
    final fields = <_Field>[];

    void add(String label, String? value) {
      if (value != null && value.trim().isNotEmpty) {
        fields.add(_Field(label, value.trim()));
      }
    }

    add('Category', item.categoryName);
    add('Brand', b.brand);
    add('Model', b.model);
    add('Serial number', b.serialNumber);
    add('Condition', BelongingCondition.labelOf(b.condition));
    if (b.quantity != 1) add('Quantity', '${b.quantity}');
    add(
      'Status',
      BelongingArchiveState.labels[b.archiveState] ?? b.archiveState,
    );

    final purchase = item.purchase;
    if (purchase?.purchaseDate != null) {
      add('Purchase date', _dateFormat.format(purchase!.purchaseDate!));
    }
    if (purchase?.priceCents != null) {
      add(
        'Purchase price',
        formatMoney(purchase!.priceCents, purchase.currencyCode),
      );
    }
    if (b.valueCents != null) {
      add(
        'Estimated current value',
        formatMoney(b.valueCents, b.currencyCode ?? 'USD'),
      );
    } else if (b.valueUnknown) {
      add('Estimated current value', 'Unknown');
    }

    add('Location', item.locationPath);

    // Receipt availability: state the fact, never invent a receipt.
    final receipt = item.receipt;
    if (receipt != null) {
      final bits = <String>[];
      if (receipt.imagePath != null && receipt.imagePath!.isNotEmpty) {
        bits.add('image attached');
      }
      if (receipt.store != null && receipt.store!.isNotEmpty) {
        bits.add(receipt.store!);
      }
      if (receipt.receiptDate != null) {
        bits.add(_dateFormat.format(receipt.receiptDate!));
      }
      add(
        'Receipt',
        bits.isEmpty ? 'Recorded' : 'Available (${bits.join(', ')})',
      );
    } else {
      add('Receipt', 'Not recorded');
    }

    final warranty = item.warranty;
    if (warranty != null) {
      add('Warranty', _warrantyLabel(item));
    }

    if (item.documents.isNotEmpty) {
      add('Documents', item.documents.map((d) => d.title).join(', '));
    }
    add('Notes', b.notes);

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          _clean(b.name),
          style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 4),
        if (fields.isNotEmpty)
          pw.Table(
            columnWidths: {
              0: const pw.FixedColumnWidth(130),
              1: const pw.FlexColumnWidth(),
            },
            children: [
              for (final f in fields)
                pw.TableRow(
                  children: [
                    pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(vertical: 1.5),
                      child: pw.Text(
                        f.label,
                        style: const pw.TextStyle(
                          fontSize: 9,
                          color: PdfColors.grey700,
                        ),
                      ),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(vertical: 1.5),
                      child: pw.Text(
                        _clean(f.value),
                        style: const pw.TextStyle(fontSize: 9),
                      ),
                    ),
                  ],
                ),
            ],
          ),
        if (item.photoPaths.isNotEmpty) _photoWidget(item.photoPaths.first),
        pw.Divider(color: PdfColors.grey300),
      ],
    );
  }

  String _warrantyLabel(ReportItem item) {
    final warranty = item.warranty!;
    final bits = <String>[];
    if (warranty.provider != null && warranty.provider!.isNotEmpty) {
      bits.add(warranty.provider!);
    }
    final expiry = warrantyExpiryDate(
      startDate: warranty.startDate,
      durationMonths: warranty.durationMonths,
      expirationDate: warranty.expirationDate,
    );
    if (expiry != null) {
      final status = item.warrantyStatus;
      final statusLabel = switch (status) {
        WarrantyStatus.active => 'Active',
        WarrantyStatus.expiringSoon => 'Expiring soon',
        WarrantyStatus.expired => 'Expired',
        null => '',
      };
      bits.add(
        'expires ${_dateFormat.format(expiry)}'
        '${statusLabel.isEmpty ? '' : ' ($statusLabel)'}',
      );
    } else {
      bits.add('no expiry recorded');
    }
    if (warranty.warrantyNumber != null &&
        warranty.warrantyNumber!.isNotEmpty) {
      bits.add('No. ${warranty.warrantyNumber}');
    }
    return bits.join(' · ');
  }

  /// Embeds the first photo, scaled to fit. Any failure (missing file,
  /// unsupported format, corrupt bytes) skips the image — a photo must
  /// never break the whole report.
  pw.Widget _photoWidget(String path) {
    try {
      final file = File(path);
      if (!file.existsSync()) return pw.SizedBox();
      final bytes = file.readAsBytesSync();
      if (bytes.isEmpty || bytes.length > 8 * 1024 * 1024) {
        return pw.SizedBox();
      }
      return pw.Padding(
        padding: const pw.EdgeInsets.only(top: 6),
        child: pw.Container(
          height: 140,
          child: pw.Image(pw.MemoryImage(bytes), fit: pw.BoxFit.contain),
        ),
      );
    } catch (_) {
      return pw.SizedBox();
    }
  }

  // -- missing-information appendix -----------------------------------------------

  pw.Widget _missingInfoAppendix(InventoryReport report) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Appendix - items with missing information',
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          'Complete these in KEEPIT to strengthen your documentation.',
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
        ),
        pw.SizedBox(height: 6),
        for (final entry in report.missingInfo)
          pw.Padding(
            padding: const pw.EdgeInsets.symmetric(vertical: 2),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Expanded(
                  flex: 2,
                  child: pw.Text(
                    _clean(entry.belonging.name),
                    style: const pw.TextStyle(fontSize: 9),
                  ),
                ),
                pw.Expanded(
                  flex: 3,
                  child: pw.Text(
                    entry.missing.map((m) => m.label).join(', '),
                    style: const pw.TextStyle(
                      fontSize: 9,
                      color: PdfColors.grey700,
                    ),
                  ),
                ),
              ],
            ),
          ),
      ],
    );
  }

  // -- disclaimer -------------------------------------------------------------------

  pw.Widget _disclaimer() {
    return pw.Container(
      padding: const pw.EdgeInsets.all(8),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      child: pw.Text(
        'This report documents information recorded by the user in KEEPIT. '
        'It is provided for personal organization and documentation '
        'purposes only. KEEPIT does not determine insurance coverage, '
        'eligibility, or reimbursement, and this report is not legal or '
        'financial advice.',
        style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
      ),
    );
  }
}

class _Field {
  const _Field(this.label, this.value);
  final String label;
  final String value;
}
